// src/pages/login/LoginPage.jsx
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faUser } from "@fortawesome/free-regular-svg-icons";
import { faLock } from "@fortawesome/free-solid-svg-icons";
import styled from "styled-components";
import { SessionStorage } from "../../utils/browserStorage";
import { cookiesOption } from "../../utils/cookiesOption";
import logo from "../../assets/images/logo2.png"
import { baseInstance } from "../../apis/instance";

const LoginPage = () => {
  const navigate = useNavigate();
  const [idPassword, setIdPassword] = useState({
    loginId: "",
    password: "", 
  });
  
  const updateIdPassword = (event) => {
    const { name, value } = event.target;
    setIdPassword({
      ...idPassword,
      [name]: value
    })
  };

  const handleLogin = async () => {
    try{
      const response = await baseInstance.post("/auth/login", {
        loginId: idPassword.loginId,
        password: idPassword.password
      });
      const accessToken = response.data.payload.accessToken;
      const accessTokenExpiresIn =
        response.data.payload.accessTokenExpiresIn;
      SessionStorage.set("expire", accessTokenExpiresIn);
      SessionStorage.set("UserToken", accessToken);
      SessionStorage.set("User_id", idPassword.loginId);
      cookiesOption.setRefresh(
        "refresh_token",
        response.data.payload.refreshToken
      );
      navigate("/")
    }catch(error){
      console.log(error);
    }
  }

  return (
    <PageArea>
      <LoginArea>
        <img
          alt="Flag 로고"
          className="Logo"
          src={logo}
          onClick={() => navigate("/")}
        />
        <RelativeArea>
          <WriteArea
            type="text"
            name="loginId"
            placeholder="아이디"
            onChange={updateIdPassword}
          />
          <Icon icon={faUser} />
        </RelativeArea>
        <RelativeArea>
          <WriteArea
            type="password"
            name="password"
            placeholder="비밀번호"
            onChange={updateIdPassword}
          />
          <Icon icon={faLock} />
        </RelativeArea>
        <LoginButton onClick={handleLogin} fullWidth variant="contained">
          로그인
        </LoginButton>
        <SortArea>
          <LinkText href="/findid" variant="body2">
            아이디 찾기
          </LinkText>
          <LinkText href="/findpw" variant="body2">
            비밀번호 찾기
          </LinkText>
          <LinkText href="/signup" variant="body2">
            회원가입
          </LinkText>
        </SortArea>
      </LoginArea>
    </PageArea>
  );
};

const Icon = styled(FontAwesomeIcon)`
  color: white;
  position: absolute;
  left: 40px;
  top: 42px;
`;

const PageArea = styled.div`
  width: 100%;
  height: 100vh;
  align-items: center;
  display: flex;
  justify-content: center;
`;

const LoginArea = styled.div`
  flex-direction: column;
  align-items: center;
  justify-content: center;
  display: flex;
  width: 400px;
`;

const WriteArea = styled.input`
  font-size: 1rem;
  color: white;
  padding-left: 50px;
  height: 60px;
  width: 350px;
  background-color: #6c6c6c;
  border-radius: 28px;
  border: 0px;
  outline: none;
  margin: 1.25rem;
  transition: 0.2s;
  :hover {
    transition: 0.2s;
    background-color: #575757;
  }
  ::placeholder {
    color: #ffffffcc;
  }
`;

const SortArea = styled.div`
  width: 100%;
  display: flex;
  justify-content: space-evenly;
`;

const RelativeArea = styled.div`
  position: relative;
`;


const LoginButton = styled.button`
  background-color: #378975;
  color: #ffffff;
  margin-top: 1.9rem;
  margin-bottom: 1.9rem;
  border-radius: 1.8rem;
  height: 60px;
  width: 400px;
  border: 0px;
  transition: 0.2s;
  font-size: 1rem;
  :hover {
    transition: 0.2s;
    background-color: #38b597;
  }
`;

const LinkText = styled.a`
  color: black;
  :visited {
    color: black;
  }
  :hover {
    color: #adb5bd;
  }
`;

export default LoginPage;

// src/views/LoginPage.vue
<script setup>
  import '../css/login.css';
  import '../assets/flag.jpg';
  import '../css/checkbox.css';
</script>

<script>
export default{
  data() {
    return {
      Signup:"src\views\SignUpPage.vue",
    };
  },
}
</script>





<template>
 <body>
  <div class="container">
      <div class="box">
        <img src="../assets/flag.jpg" width="35%" height="20%">
        <div class="box">
        <div class="login-form">
          <div class="loginbox">          
		        <ul>
			        <li><input type="text" placeholder="아이디"> </li>
			        <li><input type="password" placeholder="비밀번호"></li>	
            </ul>
            
            </div>
            <div class="checkbox">
              <div class="checkbox1">
              
                <form action="#">
                  <label for="chk1">
                  <input type="checkbox" id="chk1">
                  <i class="circle1"></i>
                  <span class="text">로그인 상태 유지</span>
                </label>
                </form>
              </div>
              <div class="checkbox1">
                <form action="#">
                  <label for="chk2">
                  <input type="checkbox" id="chk2">
                  <i class="circle2"></i>
                  <span class="text">아이디 기억하기</span>
                </label>
                </form>
              </div> 
            </div> 
            <div class="loginbox">
            <ul>          	 
			        <li><button type="button"><span>로그인</span></button></li>
            </ul>
            </div>   
	      </div>
      <div class="idpwbox">
        <a>아이디 찾기</a>
        <a>비밀번호 찾기</a>
        <a href="{{Signup}}">회원가입</a>
      </div>
    </div>

      </div>
  </div>
    
</body>
</template>

<style scoped>
   body{
    margin: 0px;
    height: 100%;
    background-color: #2c2c2c;
  }

  .container {
    margin: 0;
    padding: 0;
    width: 100%;
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    
   
    
  }
  
  .loginbox {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
    margin-top: 1vh;
  }

  .box {
    
    display: flex;
    width: max-content;
    height: 100%;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    margin: auto;
    margin: 10%;

    
  }
  img{
   margin-bottom: 15px;
   

  }

  .idpwbox{
    display: flex;
    flex-direction: row;
    width: max-content;
    height: auto;
    justify-content: center;
    color: white;
    font-size: 1vw;
 

  }

  .checkbox{
    display: flex;
    flex-wrap: nowrap;
    justify-content: center;
    width: max-content;
    height: auto;
    color: white;
    font-size: 1vw;
    white-space: normal;
  }

  .checkbox1{
    display: flex;
    flex-wrap: nowrap;
    justify-content: center;
    width: 150px;
    height: 50px;
    color: white;
    font-size: 1vw;
  }


  a{
    margin-right: 1vw;
    margin-left: 1vw;
    font-size: 1em; 
  }


</style>
