// src/pages/MyPage.jsx
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faUser} from "@fortawesome/free-regular-svg-icons";
import styled from "styled-components";
import Grass from "../components/Grass";

const MyPage = () => {
  return (
    <PageArea>
      <LeftPage>
        <UserPage>
          <ProfileArea>
            <RelativeArea>
              <FontAwesomeIcon
                icon={faUser}
                style={{width: 120, height: 120, marginBottom: 30}}
              />
              <EditProfile>Edit Profile</EditProfile>
            </RelativeArea>
          </ProfileArea>
          <NickNameArea>
            <NickName>문희조</NickName>
            <IntroduceArea>
              <Introduce>
                Hi
                <br />
                Korean Language Is Broken...
              </Introduce>
              <IntroduceTag>
                <Tag>
                  #Spring #Java #FullStack
                  <br />
                  #Be #응애
                </Tag>
              </IntroduceTag>
            </IntroduceArea>
          </NickNameArea>
        </UserPage>
        <HistoryArea>
          <HistoryContent>
            <HistoryYear>2021</HistoryYear>
            <HistoryYearList>
              <HistoryYearListItem>알고리즘 스터디(기초반)</HistoryYearListItem>
            </HistoryYearList>
            <HistoryYear>2022</HistoryYear>
            <HistoryYearList>
              <HistoryYearListItem>알고리즘 스터디(코테반)</HistoryYearListItem>
              <HistoryYearListItem>FLAG-게시판 (BE)</HistoryYearListItem>
            </HistoryYearList>
          </HistoryContent>
        </HistoryArea>
      </LeftPage>
      <RightPage>
        <GrassArea>
          <GrassName>STUDY_WEB-BACKEND</GrassName>
          <Grass />
        </GrassArea>
      </RightPage>
    </PageArea>
  );
};

const PageArea = styled.div`
  width: 100%;
  height: 82.5vh;
  display: flex;
`;

const LeftPage = styled.div`
  width: 40%;
  height: 100%;
  display: flex;
  flex-direction: column;
`;

const RightPage = styled.div`
  width: 60%;
  height: 100%;
  background-image: url(/home-book.JPG);
`;

const UserPage = styled.div`
  width: 100%;
  height: 40%;
  display: flex;
`;

const RelativeArea = styled.div`
  position: relative;
`;

const ProfileArea = styled.div`
  width: 45%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-end;
  margin-right: 40px;
`;

const EditProfile = styled.button`
  position: absolute;
  fontsize: 5px;
  color: white;
  background-color: #434343;
  height: 25px;
  width: 80px;
  left: 70px;
  top: 100px;
  outline: none;
  border-radius: 28px;
  :hover {
    background-color: #4d4d4d;
  }
`;

const NickNameArea = styled.div`
  display: flex;
  width: 55%;
  height: 100%;
  flex-direction: column;
`;

const NickName = styled.div`
  display: flex;
  height: 40%;
  font-size: 40px;
  font-weight: bold;
  align-items: flex-end;
`;

const IntroduceArea = styled.div`
  width: 100%;
  height: 60%;
`;

const Introduce = styled.div`
  display: flex;
  font-size: 20px;
  align-items: flex-end;
  height: 40%;
`;

const IntroduceTag = styled.div`
  display: flex;
  font-size: 15px;
  align-items: center;
  height: 40%;
`;

const Tag = styled.p`
  margin: 0px;
`;

const HistoryArea = styled.div`
  background-color: rgba(0; 0; 0; 0.2);
  width: 100%;
  height: 60%;
  display: flex;
`;

const HistoryContent = styled.div`
  margin-left: 20%;
  padding-top: 10%;
`;

const HistoryYear = styled.h1`
  font-size: 25px;
  padding-top: 20px;
`;

const HistoryYearList = styled.ul`
  margin-bottom: 10px;
`;

const HistoryYearListItem = styled.li`
  margin-bottom: 3px;
  list-style-type: disc;
  margin-left: 20px;
`;

const GrassArea = styled.div`
  padding-left: 80px;
  height: 100%;
  top: 700px;
  display: flex;
  flex-direction: column;
`;

const GrassName = styled.h3`
  color: white;
  padding-top: 600px;
  margin: 0;
  font-weight: bold;
`;

export default MyPage;

// src/views/MyPage.vue
<template>
  <body>
    <div class="container">
      <div class="box1">
        <div class="myinformation">
          <div class="photo">
            <p>사진</p>
          </div>

          <div class="infobox">
            <div class="info">
              <p>이름</p>
            </div>

            <div class="info">
              <p>한 줄 소개</p>
            </div>
          </div>
        </div>

        <div class="myactivity">
          <div class="actibox1">
            <div class="acti1">
              <p>2021</p>
            </div>
            <div class="acti2">
              <p>· 알고리즘 스터디 (기초반)</p>
            </div>

            <div class="actibox2">
              <div class="acti3">
                <p>2022</p>
              </div>
              <div class="acti4">
                <p>· 알고리즘 스터디 (코테반)</p>
                <P>· FLAG-게시판 (BE)</P>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="box2">
        <img src="src/assets/book.jpg" width="900" height="1200" />
        <div class="botombox">
          <p>잔디</p>
        </div>
      </div>
    </div>
  </body>
</template>

<script></script>

<style scoped>
body {
  background-color: rgba(19, 16, 16, 0.973);
  margin-top: 125px;
  width: 100%;
  height: 100%;
  align-items: center;
}

.menu {
  height: 60px;
  padding-bottom: 40px;
  margin-bottom: 20px;
  background: white;
  font-weight: bold;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  position: fixed;
  top: 0;
  /* width: 100% */
  left: 0;
  right: 0;
}

.container {
  margin: 0;
  padding: 0;
  width: 100%;
  height: 100%;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  margin: 0;
  padding: 0;
  padding-bottom: 30px;
  margin-bottom: 20px;
  border: 1px groove black;
}

.box1 {
  display: flex;
  flex-direction: column;
  width: 42vw;
  height: 113vh;
  border: 1px groove black;
  margin: 0;
  padding: 0;
}

.box2 {
  display: flex;
  flex-direction: row;
  width: 55vw;
  height: 113vh;
  border: 1px groove black;
  margin: 0;
  padding: 0;
  justify-content: center;
  align-items: flex-end;
}

.myinformation {
  display: flex;
  width: 42vw;
  height: 57vh;
  border: 1px groove rgb(62, 61, 61);
  margin: 0px;
  justify-content: space-evenly;
  align-items: center;
  margin-right: 2px;
  margin-left: 2px;
  background-color: rgb(62, 61, 61);
}

.titlebox {
  width: 40vw;
  height: 15vh;
  background-color: black;
  color: white;
  border: 2px groove white;
}

.photo {
  width: 10vw;
  height: 10vw;
  background-color: rgb(62, 61, 61);
  color: white;
  border: 2px groove gray;
  font-size: 2.8em;
  border-radius: 70%;
  text-align: center;
}

.ph {
  width: 5vw;
  height: 5vh;
}

.infobox {
  width: 20vw;
  height: 20vh;
  background-color: rgb(62, 61, 61);
  color: white;
  border: 1px groove gray;
}

.info {
  width: 20vw;
  height: 9vh;
  background-color: rgb(62, 61, 61);
  color: white;
  border: 3px groove gray;
  align-content: space-evenly;
  font-size: 15px;
}

.myactivity {
  display: flex;
  width: 42vw;
  height: 55vh;
  border: 1px groove rgb(46, 46, 46);
  background-color: rgb(46, 46, 46);
  margin: 0;
  padding: 0;
  margin-left: 0.1vw;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.actibox1 {
  width: 13vw;
  height: 5.5vw;
  background-color: rgb(46, 46, 46);
  color: white;
  border: 2px groove gray;
  justify-content: center;
  align-items: center;
  margin: 0;
  padding: 0;
}
.actibox2 {
  width: 13vw;
  height: 6vw;
  background-color: rgb(46, 46, 46);
  color: white;
  border: 2px groove gray;
  justify-content: center;
  align-items: center;
  margin: 0;
  padding: 0;
}

.acti1 {
  width: 13vw;
  height: 1.5vw;
  background-color: rgb(46, 46, 46);
  color: white;
  border: 2px groove white;
  justify-content: space-evenly;
  align-items: center;
  font-size: 10px;
}

.acti2 {
  width: 13vw;
  height: 4vw;
  background-color: rgb(46, 46, 46);
  color: white;
  border: 2px groove white;
  justify-content: space-evenly;
  align-items: center;
  font-size: 10px;
}
.acti3 {
  width: 13vw;
  height: 1.5vw;
  background-color: rgb(46, 46, 46);
  color: white;
  border: 2px groove white;
  justify-content: space-evenly;
  align-items: center;
  font-size: 10px;
}

.acti4 {
  width: 13vw;
  height: 4.5vw;
  background-color: rgb(46, 46, 46);
  color: white;
  border: 2px groove white;
  justify-content: space-evenly;
  align-items: center;
  font-size: 10px;
}

.ground {
  display: flex;
  width: 46vw;
  height: 122vh;
  border: 2px groove black;
  margin: 10px;
  flex-direction: column;
  justify-content: space-evenly;
  align-items: center;
}

.botombox {
  width: 45vw;
  height: 17vh;
  border: 2px groove gray;
  justify-content: center;
  align-items: flex-end;
  margin-right: 5px;
  margin-left: 5px;
  color: white;
  font-size: 23px;
}
</style>
